module.exports = {
  require: [
    "ts-node/register",
    // "tsconfig-paths/register",
    // "source-map-support/register",
    // "dotenv/config",
    // "reflect-metadata",
  ],
  extension: ["ts"],
  spec: ["test/**/*.test.ts"],
  timeout: 10000,
  slow: 5000,
  //   exit: true,
  //   reporter: "spec",
  //   ui: "bdd",
  //   recursive: true,
  //   "watch-files": ["src/**/*.ts", "test/**/*.ts"],
  //   "watch-ignore": ["node_modules", "dist"],
  //   watch: true,
  //   "full-trace": true,
  //   "inline-diffs": true,
  //   "no-colors": false,
  //   "reporter-options": {
  //     mochaFile: "test-results.xml",
  //     toConsole: true,
  //   },
  //   bail: false,
  //   exit: true,
  //   grep: "",
  //   invert: false,
};
