FROM node:23-alpine

ARG VERSION=latest

WORKDIR /app
ENV CLIENT_PORT=6274
ENV SERVER_PORT=6277

RUN npm install -g @modelcontextprotocol/inspector@${VERSION}

EXPOSE ${CLIENT_PORT}
EXPOSE ${SERVER_PORT}

CMD ["mcp-inspector"]